-- return {
--   -- from: https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-get-types-on-the-left-and-offset-the-menu
--   PmenuSel = { bg = "#282C34", fg = "NONE" },
--   Pmenu = { fg = "#C5CDD9", bg = "#22252A" },
--
--   CmpItemAbbrDeprecated = { fg = "#7E8294", bg = "NONE", fmt = "strikethrough" },
--   CmpItemAbbrMatch = { fg = "#82AAFF", bg = "NONE", fmt = "bold" },
--   CmpItemAbbrMatchFuzzy = { fg = "#82AAFF", bg = "NONE", fmt = "bold" },
--   CmpItemMenu = { fg = "#C792EA", bg = "NONE", fmt = "italic" },
--
--   CmpItemKindField = { fg = "#EED8DA", bg = "#B5585F" },
--   CmpItemKindProperty = { fg = "#EED8DA", bg = "#B5585F" },
--   CmpItemKindEvent = { fg = "#EED8DA", bg = "#B5585F" },
--
--   CmpItemKindText = { fg = "#C3E88D", bg = "#9FBD73" },
--   CmpItemKindEnum = { fg = "#C3E88D", bg = "#9FBD73" },
--   CmpItemKindKeyword = { fg = "#C3E88D", bg = "#9FBD73" },
--
--   CmpItemKindConstant = { fg = "#FFE082", bg = "#D4BB6C" },
--   CmpItemKindConstructor = { fg = "#FFE082", bg = "#D4BB6C" },
--   CmpItemKindReference = { fg = "#FFE082", bg = "#D4BB6C" },
--
--   CmpItemKindFunction = { fg = "#EADFF0", bg = "#A377BF" },
--   CmpItemKindStruct = { fg = "#EADFF0", bg = "#A377BF" },
--   CmpItemKindClass = { fg = "#EADFF0", bg = "#A377BF" },
--   CmpItemKindModule = { fg = "#EADFF0", bg = "#A377BF" },
--   CmpItemKindOperator = { fg = "#EADFF0", bg = "#A377BF" },
--
--   CmpItemKindVariable = { fg = "#C5CDD9", bg = "#7E8294" },
--   CmpItemKindFile = { fg = "#C5CDD9", bg = "#7E8294" },
--
--   CmpItemKindUnit = { fg = "#F5EBD9", bg = "#D4A959" },
--   CmpItemKindSnippet = { fg = "#F5EBD9", bg = "#D4A959" },
--   CmpItemKindFolder = { fg = "#F5EBD9", bg = "#D4A959" },
--
--   CmpItemKindMethod = { fg = "#DDE5F5", bg = "#6C8ED4" },
--   CmpItemKindValue = { fg = "#DDE5F5", bg = "#6C8ED4" },
--   CmpItemKindEnumMember = { fg = "#DDE5F5", bg = "#6C8ED4" },
--
--   CmpItemKindInterface = { fg = "#D8EEEB", bg = "#58B5A8" },
--   CmpItemKindColor = { fg = "#D8EEEB", bg = "#58B5A8" },
--   CmpItemKindTypeParameter = { fg = "#D8EEEB", bg = "#58B5A8" },
-- }

-- local normal = astronvim.get_hlgroup "Normal"
-- local fg, bg = normal.fg, normal.bg
-- local bg_alt = astronvim.get_hlgroup("Visual").bg
-- local green = astronvim.get_hlgroup("String").fg
-- local red = astronvim.get_hlgroup("Error").fg
-- return {
--   TelescopeBorder = { fg = bg_alt, bg = bg },
--   TelescopeNormal = { bg = bg },
--   TelescopePreviewBorder = { fg = bg, bg = bg },
--   TelescopePreviewNormal = { bg = bg },
--   TelescopePreviewTitle = { fg = bg, bg = green },
--   TelescopePromptBorder = { fg = bg_alt, bg = bg_alt },
--   TelescopePromptNormal = { fg = fg, bg = bg_alt },
--   TelescopePromptPrefix = { fg = red, bg = bg_alt },
--   TelescopePromptTitle = { fg = bg, bg = red },
--   TelescopeResultsBorder = { fg = bg, bg = bg },
--   TelescopeResultsNormal = { bg = bg },
--   TelescopeResultsTitle = { fg = bg, bg = bg },
-- }
