return {
  "CRAG666/code_runner.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  cmd = { "RunCode", "RunFile", "RunProject", "RunClose", "CRFiletype", "CRProjects" },
  opts = {
    mode = "toggleterm",
    float = {
      -- Window border (see ':h nvim_open_win')
      border = "double",

      -- Highlight group for floating window/border (see ':h winhl')
      border_hl = "FloatBorder",
      float_hl = "Normal",

      -- Transparency (see ':h winblend')
      blend = 0,
    },
    startinsert = true,
    filetype = {
      javascript = "node",
      java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
      c = "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
      zig = "zig run",
      cpp = "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
      -- objective - c= "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
      php = "php",
      python = "python -u",
      perl = "perl",
      perl6 = "perl6",
      ruby = "ruby",
      go = "go run",
      lua = "lua",
      groovy = "groovy",
      powershell = "powershell -ExecutionPolicy ByPass -File",
      bat = "cmd /c",
      shellscript = "bash",
      fsharp = "fsi",
      csharp = "scriptcs",
      vbscript = "cscript //Nologo",
      typescript = "ts-node",
      coffeescript = "coffee",
      scala = "scala",
      swift = "swift",
      julia = "julia",
      crystal = "crystal",
      ocaml = "ocaml",
      r = "Rscript",
      applescript = "osascript",
      clojure = "lein exec",
      haxe = "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
      rust = "cd $dir && rustc $fileName && $dir/$fileNameWithoutExt",
      racket = "racket",
      scheme = "csi -script",
      ahk = "autohotkey",
      autoit = "autoit3",
      dart = "dart",
      pascal = "cd $dir && fpc $fileName && $dir/$fileNameWithoutExt",
      d = "cd $dir && dmd $fileName && $dir/$fileNameWithoutExt",
      haskell = "runghc",
      nim = "nim compile --verbosity:0 --hints:off --run",
      lisp = "sbcl --script",
      kit = "kitc --run",
      v = "v run",
      sass = "sass --style expanded",
      scss = "scss --style expanded",
      less = "cd $dir && lessc $fileName $fileNameWithoutExt.css",
      FortranFreeForm = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
      fortran = "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
      sml = "cd $dir && sml $fileName",
    },
  },
}
